// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

[Table("Order_Item")]
public partial class OrderItem
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("product_id")]
    public int ProductId { get; set; }

    [Column("order_id")]
    public int OrderId { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderItems")]
    public virtual Order Order { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderItemOrderNavigations")]
    public virtual Product OrderNavigation { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("OrderItemProducts")]
    public virtual Product Product { get; set; }
}