// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Entities;

public partial class Order
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("order_date")]
    public DateOnly OrderDate { get; set; }

    [Column("order_sum")]
    public double OrderSum { get; set; }

    [Column("user_id")]
    public int UserId { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    [ForeignKey("UserId")]
    [InverseProperty("Orders")]
    [JsonIgnore]
    public virtual User User { get; set; }
}